pipeline {
    agent any

    stages {
        stage('Build Docker Image') {
            steps {
                echo "🐳 Building Docker image"
                sh '''
                    cd backend
                    docker build -t fastapi-template:latest .
                '''
            }
        }

        stage('Run Container') {
            steps {
                echo "🚀 Running Docker container"
                sh '''
                    docker run -d --rm -p 8000:80 --name fastapi-test fastapi-template:latest
                    sleep 5
                    curl -f http://localhost:8000 || echo "⚠️ App not responding"
                '''
            }
        }
    }
}
